_workspace_report() {
	:
}
_WORKSPACE_TAG_SUMMARY_HEADER=$(printf "%-${_CONF_DEV_WORKSPACE_ID_LENGTH}s%-${_CONF_DEV_WORKSPACE_TIME_SUMMARY_LENGTH}s%-${_CONF_DEV_WORKSPACE_TIME_SUMMARY_LENGTH}s" "Workspace Report" "Spent" "Estimate" "Balance")
_info "$_WORKSPACE_TAG_SUMMARY_HEADER"
for _WORKSPACE_TAG in $(_workspace_toplevel_tags); do
	_WORKSPACE_TAG_NAME=$(basename $_WORKSPACE_TAG)
	_WORKSPACES=""
	_ACTIVITY_TOTAL_TIME=0
	_WORKSPACE_TOTAL_TIME_ESTIMATE=0
	_WORKSPACE_BALANCE=0
	_WORKSPACE_TAG_HAS_WORKSPACES=0
	for _WORKSPACE_PATH in $(find $_WORKSPACE_TAG -type f -name '.context'); do
		_WORKSPACE_DIR=$(dirname $_WORKSPACE_PATH)
		_WORKSPACE_ID=$(basename $_WORKSPACE_DIR)
		_WORKSPACES="$_WORKSPACES $_WORKSPACE_ID"
		_workspace_time_count -name 'current-*'
		_WORKSPACE_ACTIVITY_DIR=archived _workspace_time_count
		. $_WORKSPACE_PATH
		_time_human_readable_to_seconds $_WORKSPACE_TIME_ESTIMATE
		_WORKSPACE_TOTAL_TIME_ESTIMATE=$(($_WORKSPACE_TOTAL_TIME_ESTIMATE + _TIME_IN_SECONDS))
		_WORKSPACE_TAG_HAS_WORKSPACES=1
	done
	if [ $_WORKSPACE_TAG_HAS_WORKSPACES -eq 1 ]; then
		_WORKSPACE_BALANCE=$(($_WORKSPACE_TOTAL_TIME_ESTIMATE - $_ACTIVITY_TOTAL_TIME))
		_time_seconds_to_human_readable $_WORKSPACE_BALANCE
		_WORKSPACE_BALANCE_HUMAN_READABLE=$_HUMAN_READABLE_TIME
		_time_seconds_to_human_readable $_WORKSPACE_TOTAL_TIME_ESTIMATE
		_WORKSPACE_TOTAL_TIME_ESTIMATE_HUMAN_READABLE=$_HUMAN_READABLE_TIME
		_time_seconds_to_human_readable $_ACTIVITY_TOTAL_TIME
		_ACTIVITY_TOTAL_TIME_HUMAN_READABLE=$_HUMAN_READABLE_TIME
		_WORKSPACE_TAG_SUMMARY=$(printf "%-${_CONF_DEV_WORKSPACE_ID_LENGTH}s%-${_CONF_DEV_WORKSPACE_TIME_SUMMARY_LENGTH}s%-${_CONF_DEV_WORKSPACE_TIME_SUMMARY_LENGTH}s" "$_WORKSPACE_TAG_NAME" $_ACTIVITY_TOTAL_TIME_HUMAN_READABLE $_WORKSPACE_TOTAL_TIME_ESTIMATE_HUMAN_READABLE $_WORKSPACE_BALANCE_HUMAN_READABLE)
		_detail "$_WORKSPACE_TAG_SUMMARY"
		_WORKSPACE_TAG_WORKSPACES=$(printf "%-10s%s" "" "$_WORKSPACES")
		_detail "$_WORKSPACE_TAG_WORKSPACES"
	fi
done
